#define LCD_BACKGROUND_R  124
#define LCD_BACKGROUND_G  254
#define LCD_BACKGROUND_B  57

#define LCD_PITCHED_R  24
#define LCD_PITCHED_G  52
#define LCD_PITCHED_B  10

#define LEFT_DISPLAY   388
#define TOP_DISPLAY	   33
#define RIGHT_DISPLAY  605
#define BOTTOM_DISPLAY 166